(add-to-list 'eshell-command-aliases-list (list "l" "ls -ha"))
(add-to-list 'eshell-command-aliases-list (list "t" "terraform"))
(add-to-list 'eshell-command-aliases-list (list "tp" "terraform plan"))
(add-to-list 'eshell-command-aliases-list (list "ta" "terraform apply"))
(add-to-list 'eshell-command-aliases-list (list "td" "terraform destroy"))
(add-to-list 'eshell-command-aliases-list (list "tw" "terraform workspace"))
(add-to-list 'eshell-command-aliases-list (list "tws" "terraform workspace select"))
(add-to-list 'eshell-command-aliases-list (list "ti" "terraform init"))
(add-to-list 'eshell-command-aliases-list (list "tf" "tfenv"))
(add-to-list 'eshell-command-aliases-list (list "gc" "gcloud compute"))
(add-to-list 'eshell-command-aliases-list (list "g" "gcloud"))
(add-to-list 'eshell-command-aliases-list (list "k" "kubectl"))

