# limit coredumpsize 0

#typeset -U path
#path=($path /usr/*/bin(N-/) /usr/local/*/bin(N-/) /var/*/bin(N-/))

# export RSYNC_RSH=ssh
# export CVS_RSH=ssh
source "$HOME/.cargo/env"

# Gcloud ENV Config
export GCP_PROJECT=$(gcloud config get-value core/project)

## Terraform project variable value
export TF_VAR_project=$(gcloud config get-value core/project)
